import { ThemeProvider } from "@/components/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";


import {
  Open_Sans,
  Montserrat,
  Roboto,
  Poppins,
  Inter,
  Lato,
  Raleway,
} from "next/font/google";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "700"] });
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] }); // Added weight: 400 and 700
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] }); // Added weight: 400 and 700
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] }); // Added weight: 400 and 700
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.className} ${montserrat.className} ${roboto.className} ${poppins.className} ${inter.className} ${lato.className} ${raleway.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
